### ISSUE TITLE
Servers are too bad 

### ISSUE THREAD

**Issue by konoashi** [Moe03/HyskyAPI#2]
Your servers crash when I send more than 5 requests per seconds...

**Comment by konoashi** [comment]
can i get the code to host myself ?

**Comment by Moe03** [comment]
Alright, choosing hostinger wasnt so wise from me but it was surely
affordable. If you can host the API yourself that will surely fix the
problem.

**Comment by Moe03** [comment]
Files are uploaded feel free to host them yourself, then contact me to update the API info on Skyah.

**Comment by konoashi** [comment]
thank you :)
